### ISSUE TITLE
Separate first graph into 2 graphs: total spending and spending per capita

### ISSUE THREAD

**Issue by rufuspollock** [datasets/pharmaceutical-drug-spending#1]
Current first graph on https://datahub.io/core/pharmaceutical-drug-spending is unreadable for per capita spend because it is dwarfed by total spending:

![image](https://user-images.githubusercontent.com/180658/34914782-7acb70be-f911-11e7-8c0a-0b563274667f.png)

* EITHER: have a graph with two separate scales (not sure how we do that)
* OR: (easier probably) have two separate graphs

Also: units for total spending graph are not clear. I think we need to label y axis as spending in millions ... (i had to work this out by looking further down at that column)

**Comment by Mikanebu** [comment]
FIXED, separated into 2 graphs(total spending and spending per capita) and updated title to `Total spending by country 2015(in millions of dollars)` since `y axis` is always column name. It is live now on https://datahub.io/core/pharmaceutical-drug-spending

**Comment by rufuspollock** [comment]
@Mikanebu 👏 good work.

Is there no way to change the axis labelling separate from changing the column name? /cc @anuveyatsu

**Comment by rufuspollock** [comment]
@Mikanebu one small bug: Total spending by country 2015(in millions of dollars) should have a space before bracket: Total spending by country 2015 (in millions of dollars).

**Comment by anuveyatsu** [comment]
> Is there no way to change the axis labelling separate from changing the column name? /cc @anuveyatsu

@rufuspollock no, you can see it here - https://github.com/frictionlessdata/datapackage-render-js/blob/master/lib/view.js#L84-L86

**Comment by Mikanebu** [comment]
@rufuspollock Thanks for reporting this. Fixed
